#!/bin/bash
clear
m="\033[0;1;36m"
y="\033[0;1;37m"
yy="\033[0;1;32m"
yl="\033[0;1;33m"
wh="\033[0m"
red='\e[1;31m'
green='\e[0;32m'
CYAN='\033[0;36m'
echo -e "\E[44;1;39m MENU UTAMA              \E[0m"
echo -e "\E[0;41;36m          Script Mod By Saunkancil         \E[0m"
echo -e "             ═══[Trojan]═══"
echo -e " =============================="
echo -e " 1)  Menu Trojan Account"
echo -e " 2)  Perbarui Cert"
echo -e " 3)  Bersihkan Ram"
echo -e " 4)  Restart Service"
echo -e " 5)  Cek Akun Aktif"
echo -e " 6)  Bacukup Data "
echo -e " 7)  Speedtest VPS"
echo -e " 8)  Cek Service Trojan"
echo -e " 9)  Restart VPS"
echo -e " =============================="
read -p "Select From Options [ 1 - 1o ] : " menu
case $menu in
1)
menu-trojan
;;
2)
cert.sh
;;
3)
clear-ram
;;
3)
clear-log
;;
4)
xp
;;
5)
delexp
;;
6)
backup
;;
7)
speedtest
;;
8)
cek-service.sh
;;
9)
restart
;;
*)
clear
menu
;;
esac
